name: Spectate
main: com.Chipmunk9998.Spectate.Spectate
version: 1.7.1
commands:
    spectate:
        description: Lets you spectate another user
    spectateoff:
        description: Stops you from spectating and returns you back to your original location
    spec:
        description: Lets you spectate another user
    specoff:
        description: Stops you from spectating and returns you back to your original location